Repository rishivyas1969/CandleStick-Chart, pull requests merged in 2021-10, with the labels that each got.

#1 APPL -> TSLA
  templates/home.html
Labels: hacktobesfest-accepted

#2 Update README.md
  README.md
Labels: hacktoberfest-accepted

#3 pigeon
  main.py
Labels: hacktoberfest-accepted, hacktoberfest

#4 Added some shits
  templates/about.html
  templates/home.html
Labels: hacktoberfest-accepted, hacktoberfest
